export const GET_ALL_ITEM = 'GET_ALL_ITEM';
export const GET_ALL_ITEM_SUCCESS = 'GET_ALL_ITEM_SUCCESS';
export const GET_ALL_ITEM_FAIL = 'GET_ALL_ITEM_FAIL';

export const CHANGE_ITEM = 'CHANGE_ITEM';
export const CLEAR_ITEM = "CLEAR_ITEM";

export const FILTER_TIME = "FILTER_TIME";
export const COMPLETE_FILTER = "COMPLETE_FILTER";

export const SET_CHACKED_SUCCESS = 'SET_CHACKED_SUCCESS';
export const SET_CHACKED_FAIL = 'SET_CHACKED_FAIL';
